language: node_js
node_js:
- stable
addons:
  ssh_known_hosts:
  - rey.webhouse.net
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
before_deploy:
- openssl aes-256-cbc -K $encrypted_205f6da18cc3_key -iv $encrypted_205f6da18cc3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: bash scripts/service-deploy.sh dev $TRAVIS_BUILD_DIR
  skip_cleanup: true
  on:
    branch: dev
- provider: script
  script: bash scripts/service-deploy.sh master $TRAVIS_BUILD_DIR
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    recipients:
    - cb@webhouse.dk
    on_success: never
    on_failure: always
  slack:
    secure: st1+6t/PrbhqtY7Y5rTHPKk4Zs990PDVE7aCinyuEcI/tOwBCjfI8p9R0hM45JgRThG7exJNsWitUmqjGiHoiFoYe80dkiUKdRo2lHIIt2VIC7sec8n6VjrlwI379kKoSgaSts9k59RW8Oldkf+qvUMjLaAri2ICiN2WgtL74xGcrkwo7jH6LNgsoe+EtYnGKP4XKLvGXGCWod0uqCWlBFau/38dFPNEeGWuBP9gxjLtxzKcdgu7V9YUXxdYWXnzKZJORwBK98GiWAAdxZHQ9/a5g3mqTGWZgP/7bWYlWUGAz1LKoeBWxpGUqU8z4SMUcpJk7w2/gHNP5AjgKYZElzTXVW6f9g+hZJAr7ZlkJj0wzDZCAW9vG47ABiSDGUSSqvvygV9Ver7TTk9UF+O5jQ3mYYQ7HASVspVZBKa3W9HwuertlnceLPQQpazHgjB5UuzeoGQ/rmJrsYevYjk+f+uKS49ZSAAsUAx3fOFpqfddapMp3RVHZT+z0feuo+aiAWbpRh6N2OaTee8ytY4PtN7NCRVs7NH+ACJTspUghDi+nf6hjF5nxE4I750ww4QyMbAG3uwFSHkIu+WcyWIyfajC11H64ZebwnFdzZp+vvTjKqGeTIsETpoQZxypFtOyUXOWtNsEx8eUDPpvRMvqtZDKu4rVX//t4UUwoImIDPA=
